### ISSUE TITLE
Typography is not defined in a global style sheet

### ISSUE THREAD

**Issue by adrianpawlik** [cephiednomiko/odds-table#2]
https://github.com/cephiednomiko/odds-table/blob/19ea59ade2c7ae7b93b1b9ad5dc0e881c4c98b0b/src/styles/row.scss

We have different font sizes defined in separate style sheets. Wouldnt it be better to have a global configuration for this? What would you propose? An inheritance or a class that you add in a markup, i.e font-small, font-header?

**Comment by cephiednomiko** [comment]
I've chosen using global modifiers (BEM style) with variables as a solution to this. Using additional classes in markup might've been easier, but would collide with BEM methodology. Might've also used @extend inheritance if I decided to first declare font clasess, but instead using them, inherit their font-size in specified elements (thought it would be overkill).
