### ISSUE TITLE
Breakpoints are defined in multiple places

### ISSUE THREAD

**Issue by adrianpawlik** [cephiednomiko/odds-table#3]
https://github.com/cephiednomiko/odds-table/blob/19ea59ade2c7ae7b93b1b9ad5dc0e881c4c98b0b/src/styles/options.scss#L13

What would you propose here? You have defined the breakpoint in many places, what difficult to maintain in the future? Could we have a mixin for this?

**Comment by cephiednomiko** [comment]
For a full-sized project, I would declare breakpoints with min-width and max-width set (to target only specific breakpoint with styles), but for this task I decided to go with only max-width (as most styles for tablet breakpoint were also used on mobile).
